services:
  app:
    platform: linux/amd64
    build:
      context: .
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    container_name: pm25
    tty: true
    volumes:
      - type: bind
        source: .
        target: /work
      - type: volume
        source: packages
        target: /usr/local/lib/python3.11/site-packages

volumes:
  packages:
